version: '3'

services:
  ariscorp-website-ptu:
    build:
      context: ../../
      dockerfile: docker/ptu/Dockerfile
    image: ariscorp/ariscorp-website:ptu
    platform: linux/amd64
    ports:
      - '3002:3000'
